### ISSUE TITLE
Server crash after restart 

### ISSUE THREAD

**Issue by rsquatre** [Dunkmania101/SpatialHarvesters#13]
Hi, I added SpatialHarvesters to ATM6 1.16.3 (not sure if the bug comes from that or not), it worked fine until I had to restart the server, it now crashes straight after world loading.
Bug happens on both 0.7.8 and 0.7.9.
I have 1 Ore Harvester and 1 Soil Harvester placed in the same chunk with one of your chunkloaders.

Crash report: https://pastebin.com/NU9NBBWd
Tell me if you need anything else, thanks for your work.

**Comment by Dunkmania101** [comment]
If you don't feel like reading the wall of text below, basically I think I fixed it and the new version will be out soon.

It looks like a single tick took an entire minute to complete (they're not supposed to exceed 1/20 of a second). The log also said something about how I was getting the harvesters to determine their energy capacity based on the tier of their block. Basically, they need to know what block they are in order to do that but, at least to my knowledge, the only way to do that from a tile entity can't be done until it's already loaded. My solution was to have it set its energy capacity, speed (which actually means slowness, since it's a measure of how long it takes to run), and price to the largest integer Java would allow and then correct it once it was ready. The log seemed to complain about where I was putting that check (it was a thing Forge would handle, it's called "onLoad"). I've changed it to do this every tick since I know it can handle it there and the whole operation is pretty small. It'll be out soon, so I'll close this now. Feel free to reopen if it keeps happening. Thanks for reporting!

**Comment by Dunkmania101** [comment]
P.S. I have a life and am not constantly monitoring these things, I've just gotten really lucky with the timing of the issues and when I'm around to see them :)
