### ISSUE TITLE
Feature / Request

### ISSUE THREAD

**Issue by YOYOK9** [Dunkmania101/SpatialHarvesters#17]
Would be a useful feature if you could show the usage of each harvester. For example the ore miner. if you looked at the uses (right click) in JEI it would show all the ores that could be collected at that level of harvester. And so on. Another is the mob harvester. what drops each mob has a chance to drop.

**Comment by Dunkmania101** [comment]
I was going to say that it's not really needed because of mods like Just Enough Resources (JER), which, for example, shows mob drops (the Mob Harvester doesn't have a custom loot table, it just drops whatever the configured mob would have, including player kill drops). However, something like the Bio Harvester is less obvious, so I think I'll just add it for all of them if I can. Thanks for the suggestion!

**Comment by Dunkmania101** [comment]
On second thought, it might not work, since the Harvesters don't determine their drops until they load and the Mob Harvester doesn't even have remotely predictable outputs, since it's based on simulating a mob dropping its items. If I later find it more doable, I'll try to add it. I'll describe how to determine what items are in the tags of each Harvester on the mod page though. Sorry!
