### ISSUE TITLE
Add a way to make certain items more rare

### ISSUE THREAD

**Issue by ghost** [Dunkmania101/SpatialHarvesters#18]
First of all thanks for making this mod! I was really excited to see a mod like this one for newer Minecraft versions!

I'd like to suggest adding a method (be it config or in-game) of making certain items be more rarely found than others. I have Silent's Gems in my modpack (which adds a LOT of ores to the game), and setting up an Ore Harvester produces a large amount of Gem ores which in turn limits the number of vanilla and Mekanism ores that are harvested.

I know I could add the SIlent's Gems ores to the blacklist, but I'd still like them to be harvested, just at a lower rate compared to the other mods I have installed.

Another thought I had would be to add a "Gems Harvester", that only harvests things like Diamond, Emerald, Quartz, etc. that would be configurable where I could have it harvest the Gem ores instead of the Ore Harvester.

**Comment by Dunkmania101** [comment]
I had a world where I had the exact same gem-overflow problem. I don't think it'd be a good idea to add that ingame since people could abuse it to prioritize really rare stuff, but I'll try to make it a config option.

**Comment by ghost** [comment]
Agreed and sounds good! Would it be possible to use some kind of weight system that is configurable?

**Comment by Dunkmania101** [comment]
That's what I had in mind!

**Comment by Dunkmania101** [comment]
_Thanks to Java being a bit paranoid about data types, I can't have a list with both numbers and strings in it. That means that there's no good way to store both the registry name it the item (e.g. ["minecraft", "dirt"] in the case of the whitelists/blacklists) and the weight, at least that I can think of. I guess I could store the number as a string, like "1" vs 1, but that's kind of sketchy and people might not put numbers in the string. I'm sure that could be checked and ignored if invalid, but still. To clarify, the lists that are in the *.toml file are generated and interpreted by/in Java, I just tell it what to say in the comment, what type of thing to store and what the default value should be and it handles the rest. If I find something better, I'll try it, but for now, I think it'll just have to wait. You can use the blacklist and use other means to obtain the gems, I guess. Sorry!_

Change of plans, I'll make it so you can disable a certain -ore- *resource* ingame and it'll output nothing but still consume power if it picks that one. That should make it still balanced since it won't affect the probability of getting the other items and won't make it cheaper to run.
