### ISSUE TITLE
Mob Shards not dropping from Specific Mob Harvester - v0.9.3 for 1.16.3

### ISSUE THREAD

**Issue by Whacker007** [Dunkmania101/SpatialHarvesters#20]
Hi there, using 0.9.3 of your mod for 1.16.3.  The Specific Mob Harvester doesn't ever output any mob shards, even if I set the chance to 1 in the config.  I checked this code repository and it looks like the if statement for the mob shard drop never fires because of the conditions, which are also different from the other spatialharvester.java regular shard drop triggers.  Can you give that a look please?  As a suggestion, for the mob harvesters, maybe just remove the shard7 drop all together and just make it so they only drop mob shards.  Thanks for the awesome mod.

**Comment by Dunkmania101** [comment]
Weird, I thought it worked fine from my tests. I'll change it anyway, just in case. Plus I've been looking for an excuse to do an update because the file names were inconsistent (only 1.16.3 had "forge" in the name, something I had meant for them all) :)

Hey, at least it's better than 0.9.2, where none of the harvesters were working because of how I was checking the configurable tags!

**Comment by Dunkmania101** [comment]
Done!

**Comment by Whacker007** [comment]
Now that's what I call some rapid turnaround time!  Confirmed it's fixed, I'm getting mob shards now.  Cheers mate.
