### ISSUE TITLE
Oh No!!! Don't quit Forge

### ISSUE THREAD

**Issue by papaworld** [Dunkmania101/SpatialHarvesters#22]
Hi, super mod. It is high on my list!

You mentioned on Nov 25th your Forge version is "done" because ET came out for Forge.

NO! PLZ! - I'm not a fan of ET and do not, nor want, it as a mod... nothing against it... it is just not for me.

Spatial is FANTASTIC! - Please keep Forge version going.

Tx

**Comment by Dunkmania101** [comment]
I was actually planning on still supporting the Forge version for bug fixes and new game versions and stuff. Managing multiple versions is a bit tedious but not too bad, since a lot of stuff is the same throughout them, just with different mappings, which basically means the main difference between a 1.15.2 release and a 1.16.4 one is the Forge version I build the jar file with, rather than the code inside. The same should hold between Forge and Fabric.
I still feel like ET is higher quality art-wise and fancier with the multiblocks, but it does lack the mob farming stuff and the nano beacons seem to be missing in the newer versions. The Dimensional Applicator is the equivalent of those. I suspect that my art is a lot nicer overall than how I see it, since my view of it is probably ruined by the "oh look, that thing that I made and know the entire inner workings of" effect.

If that Patchwork project ever gets to the point that it can reliably run all Forge mods on Fabric, I'll probably ditch it then, since I do think Fabric has more power to it and seems to run faster, not to mention all the drama with the leaders of Forge.
My god, that was all in one giant sentence!

I always seem to end up writing a wall of text in my responses :)
Also, thanks for the praise! It feels good to know someone likes what I've made!

I'll close this and pin it, just in case.

**Comment by papaworld** [comment]
The art-work, function and operation of your Spatial Harvesters mod is unique and very creative approach, well done. Forge "drama" has been around quite a while to the dis-service of modders, like you, and to the MineCraft community overall. Their general attitude needs some space ripping in my opinion. But, I prefer forge over fabric by far. The chunk loader is a very helpful and welcome addition.

Anywho... I went through the Spatial config file seeing whitelist and blacklist lines per Harvester type. Is there a way to blacklist ALL in a short command like "*" and then I can whitelist only the item(s) preferred?

**Comment by Dunkmania101** [comment]
Actually, no! I'll add that, thanks for the idea!

**Comment by Dunkmania101** [comment]
Wait, nevermind. You can do that by removing the tags from the list since that's where everything that isn't manually added comes from.

**Comment by papaworld** [comment]
Is that the last line of the toml code:?
 		custom_ore_tags = [["forge", "ores"]]

Modifying this to:
		custom_ore_tags = [["forge", "ores", "uranium", "yellorium"]]

Would this change make the harvester only dispense "forge:ores/uranium" and "forge:ores/yellorium"?

**Comment by Dunkmania101** [comment]
Close, you would remove the forge, ores tag altogether and just add the tags you want. Also, custom item outputs are in their own list. I should also add that the syntax isn't to add more entries after the two, it's to add more lists of two entries each. For example, [["forge", "a_tag_from_forge"], ["minecraft", "a_tag_from_minecraft"], ["mekanism", "a_tag_from_mekanism"]]. It's the same for items, just with the item's registry name instead of a tag. I guess another way of looking at it is minecraft:dirt and minecraft:stone is written as [["minecraft", "dirt"], ["minecraft", "stone"]].

**Comment by papaworld** [comment]
Gotchya! ThanX for your explanation. The Ore Harvester works just as you mentioned.

**Comment by MSandro** [comment]
I realy look forward for an Fabric Version of this mod. Are there any plans for when this will be published?

**Comment by Dunkmania101** [comment]
Not specifically. I think it's almost done, most of the remaining work should be registering everything (telling the game to actually add the blocks and items and stuff based on all the other code).
Thankfully, the models and textures are consistent between Forge and Fabric, since they're essentially just texture packs in a jar file. That would be a painful amount of refactoring!
I'd actually kind of forgotten about it. Not exactly forgotten, more like stopped while planning to finish at "some point".
Anyway, I'll keep working on it!

**Comment by Dunkmania101** [comment]
It looks like it was closer than I thought! I just finished it, the only part that still doesn't work it the config file, which gets generated without anything in it for some reason. I just published it to CurseForge, new projects usually take about a day to get approved (it's separate from the Forge version).

**Comment by Lortseam** [comment]
First of all, I'm the developer of the config library you are using (CompleteConfig). Nice to see that it's used in this quite popular mod!

> the only part that still doesn't work it the config file, which gets generated without anything in it for some reason.

That's because all of the fields in your config class are static, and static fields were not included so far. Luckily, I just updated my library to version 0.11.0 which now also includes static fields. So updating to that version should make your config work as expected. If you are still having trouble, feel free to reply!

**Comment by Dunkmania101** [comment]
Yay! I had noticed that it worked when they weren't static, just couldn't find a good way to access them like that. Thanks!
I suppose this isn't related to the config library, but worth a shot:

It seems like the c/common tags domain for Fabric doesn't have anything defined in it by default. For example, the ores tag is listed in the wiki, but the ore harvesters don't output anything unless I define it in that tag manually. Is that indeed the case and I have to add them manually (or use another library that defines them for me (or something (nested braces and comedy))) or am I missing something? I suppose you might know, you seem to have more Fabric experience than me :)

**Comment by Lortseam** [comment]
I'm sorry but I can't help you there. I do have some experience with Fabric, but it's mostly about mixins and that stuff, and not about adding new content to the game.
If you didn't try that already, I would recommend you to just ask that question on the Fabric Discord server.

**Comment by Dunkmania101** [comment]
No problem. I'm pretty sure that is indeed the case anyway, plus adding the tags manually did work. Thanks for adding the static field support!
