### ISSUE TITLE
[Fabric] no crafting recipes shown in REI

### ISSUE THREAD

**Issue by MSandro** [Dunkmania101/SpatialHarvesters#24]
Thank you very much for porting this mod to Fabric.
I've tested some of the harvesters in creative mode, they seems to work well, but I noticated that I can not view the recipes.

**Comment by Dunkmania101** [comment]
Which recipes? The ones to make the harvesters and such or something more like their outputs? I know the second one doesn't work, since it would require manual integration. The actual crafting recipes would be weird, though. I did notice that a lot of the crafting recipes that use tags are broken because I forgot to update them not to use the forge group (the equivalent in Fabric is the letter c), I'll fix that soon.

And you're welcome!

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/105047505-b551c400-5a6a-11eb-9362-0c4bd95d50d0.png)
I meant I am not able to show the recipe for the harvesters, yes. Tested in spatialharvesters_fabric_1.16.x-0.10.2a
It just shows me the block drop in REI but not the "Crafting Recipe"

**Comment by Dunkmania101** [comment]
I think I found the problem. Fabric has a standard for common tags being labeled with a "c", but it seems like it doesn't actually define what those tags should contain. For example, there's a standard "c:ores" tag for ores, but I'm pretty sure it doesn't automatically contain anything, although I could be wrong. I might have to populate it manually or with a library.

**Comment by Dunkmania101** [comment]
Should be fixed in 0.10.3, along with the config. Thanks!
