### ISSUE TITLE
[1.16]. Mixin error on startup

### ISSUE THREAD

**Issue by kwpugh** [Dunkmania101/SpatialHarvesters#26]
Hi again.  Not a crash or anything, but one of your mixins errors out.

log: https://gist.github.com/kwpugh/3f7b8f5a4523d5f02f9ebeeda22fba93

**Comment by Dunkmania101** [comment]
Yeah, I saw that one. I figured it would be fine, if a little annoying, since it still works. It's because that mixin class extends ServerWorld which was the only way I could find to get to other methods from within the one I was injecting into. Unfortunately, I don't know of any way to shut it up, either. Maybe one of those Suppress annotations? Would that go at the top of the class? Not sure. Anyway, feel free to let me know if it causes any problems. Thanks!
