### ISSUE TITLE
[1.15.2] Applicator effects and activators

### ISSUE THREAD

**Issue by Bass2style** [Dunkmania101/SpatialHarvesters#3]
Hi,

i noticed some things with the new Applicator system,

- Regeneration 3 is acting weird, the effect seems applied, but isn't working, but when you break the Space Ripper, the Applicator, or the Activator itself, you're regenerating.
- NightVision is a bit glitchy, you see the sky slightly flashing, i thing that setting something like 15 seconds of effect should fix that, but i'm not sure. (it seems flashy when the counter resets.)
here's a vidéo where you can see what happens : https://youtu.be/jgk1S5_OhKI  (actually uploading)

Speed, Resistance and Jump Boost have no crafts, but other Activators have multiple crafts, idk if it's an error or intended.

and a less important issue, some localisation names are not défined, Jump Boost and Night Vision activators have that problem.

have a nice day. :D

**Comment by Dunkmania101** [comment]
'Twould seem I've made a few goofy mistakes (because no one's stupid around here :D).
The regeneration issue may have been because of the amplifier being set to three. I looked it up, and although there's supposedly support for higher levels than 2, the game itself only provides a maximum of that from potions, etc.
The night vision might be fixed by slowing down the operations to, say, every 100 ticks (5 seconds).

As for the recipes and localization, good old human error is to blame! The extra recipes for other activators are where I forgot to change the output after copying the file (I'm not going to manually type everything every time! <Smiley Face>).
Both missing names are from typos. Both were missing "_activator" at the end and "night_vision" was spelled "night_nision".

I'll release a fix for these "goofy mistakes" in a moment. Hopefully, they'll all be fixed. Have a nice... section of time out of the 24 hours in Earth's revolution relative to when you read this!

**Comment by Bass2style** [comment]
we all make mistakes and errors, no one to blame, no problems with that. :p

i'm trying that out when availlable, and give my feedback. :D

thanks for your reactivity and quick support. it's not enough said. ^^

i like your humor. (and it's 14h12 here, i'm from Belgium. ^^)

**Comment by Dunkmania101** [comment]
I think the issues should be fixed, so I'll close this issue. If I missed something, please open a new issue or reopen this one, depending on whether what you find is related to this or not. Thanks!
