### ISSUE TITLE
Ore harvester does not provide glowstone?

### ISSUE THREAD

**Issue by LuciusV** [Dunkmania101/SpatialHarvesters#39]
Unlike another similar mods (Env tech, IE laser drill...) seems there is no glowstone from spatial harvesters. Although I assume one can use custom_ore_tags in config, please make ore harverster to pull glowstone blocks :)

**Comment by Dunkmania101** [comment]
I'd be adding that to the default config value, which is kind of like adding it to the config file. I noticed there isn't a tag for glowstone blocks, just for the dust, so it would have to go in as a custom item, rather than a tag. I'll add it in 0.11.6, although you'll either have to add it manually or let the file regenerate for it to take effect.

**Comment by LuciusV** [comment]
custom_ore_tags = [["minecraft", "glowstone"]] does not bring it now in 0.11.5, does it require next version to work?

**Comment by Dunkmania101** [comment]
No, the problem is that that isn't a tag, that's an item. You'll have to add that value to the... ***looks through own code to find variable name*** ...custom_ores variable.

For example:
`custom_ores = [["minecraft", "glowstone"]]`

If you still want the other custom ores to generate, you'd need to add the " , ["minecraft", "glowstone"]," part to the existing list.

For example:
`custom_ores = [["examplemod", "example_ore"], ["this_is_not_a_real_mod", "this_is_not_a_real_ore"], ["minecraft", "glowstone"]]`

**Comment by Dunkmania101** [comment]
I've released 0.11.6 with the new default!
