### ISSUE TITLE
Descriptions don't fit in GUI

### ISSUE THREAD

**Issue by Wlnfr** [Dunkmania101/SpatialHarvesters#41]
As said in the title, descriptions don't fit in the inventory GUI with GUI scale set to 2,3 and 4, making them unreadable.
Tested with: fabric-api-0.30.3+1.16 | spatialharvesters_fabric_1.16.x-0.11.6a
Here are the screenshots for all GUI scales from 1 to 4 and F3 screen for system information. Also, I am not sure if this matters, but my monitor is an old 4:3 ratio one, not 16:9/16:10.
![2021-02-28_15 00 35](https://user-images.githubusercontent.com/8050905/109419402-f5935300-79d5-11eb-9a60-6e8322d23853.png)
![2021-02-28_15 00 45](https://user-images.githubusercontent.com/8050905/109419404-f75d1680-79d5-11eb-92f3-c2b2d27c96b3.png)
![2021-02-28_15 00 52](https://user-images.githubusercontent.com/8050905/109419407-fb893400-79d5-11eb-81ca-cb8cd58e1fd0.png)
![2021-02-28_15 00 58](https://user-images.githubusercontent.com/8050905/109419410-ff1cbb00-79d5-11eb-90e8-05805cc7f9a4.png)
![2021-02-28_15 01 27](https://user-images.githubusercontent.com/8050905/109419412-017f1500-79d6-11eb-8258-096cadd81bc4.png)

**Comment by Dunkmania101** [comment]
I think someone had a similar issue a while back with the Forge version. The fix was to use a later version of Forge itself where they'd added wrapping to long tooltips. Here's a Fabric mod that does the same: [Mod](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)

I'll close this since it's essentially fixed by that. I'll also pin it since it's a pretty noticeable effect.
