### ISSUE TITLE
Incompatible with 1.17

### ISSUE THREAD

**Issue by Neubulae** [Dunkmania101/SpatialHarvesters#48]

**Comment by Dunkmania101** [comment]
I'm working on updating it. I have to rename a bunch of stuff because the mappings changed and the config API I'm using has also been updated, so I have to adapt to that. I can't do anything for Forge yet, just Fabric for now. Thanks for the reminder, though. I might have forgotten for a while without it :)

I'll close this once it's out, since technically the issue described here still exists.

**Comment by Dunkmania101** [comment]
I think I've finished the port!

I say I think because I can't build it right now because the Fabric maven is down, so there could be something left to do that I missed and would see if I tried to build it because it would fail and complain and tell me what was wrong and long run on sentences and fourth wall breakage and... comedy.

Jokes aside, I'll try to get it out once they're back online.

**Comment by Dunkmania101** [comment]
I just checked and I think they might finally be back. I'll try to get it out. I found some more code that needs updated though.

**Comment by Dunkmania101** [comment]
I just remembered that I already did this.
