### ISSUE TITLE
Other mod Energy

### ISSUE THREAD

**Issue by Shockks** [Dunkmania101/SpatialHarvesters#52]
using this mods heat gen works great if it is right up against the harvester. I've tried generators from other mods and they dont work when applied like this. Also, the energy cables from other mods dont "connect" to the harvester either. is this a bug? unable to use any energy other than from the gen included.

**Comment by Dunkmania101** [comment]
If you're using the Fabric version in 1.17, it probably won't connect to much yet because parts of the Reborn Energy API are being remade. Generators and cables from mods using that API, such as Tech Reborn itself, should work eventually, but for now it might be a bit limited. There's not really anything better I can do about it on my end. My suggestion for the time being would be to increase the speed of the heat generators in the config file, assuming speed is what you want. Come to think of it, an energy harvester could be an interesting idea! Anyway, I'll close this because of what I said above.
