### ISSUE TITLE
Crashing when placing Harvesters

### ISSUE THREAD

**Issue by MLMII** [Dunkmania101/SpatialHarvesters#9]
Minecraft:  1.16.3
Forge:  34.1.7
Spatial Harvesters 1.16.3-0.6.1

When placing an Ore Harvester(1) the world crashes; I have two logs; the first is from a played in survival world and the second is from a fresh creative world; in the first I placed the harvester on a hopper that fed into a chest and in the second I set it down on a sand block.

I suspect it may be caused by one of Xaero's Maps as I had a similar issue in 1.15.2 with another mod so I'll leave an issue ticket with them as well. 

--Thank you very much.

[crash-2020-10-04_22.20.19-server.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5325237/crash-2020-10-04_22.20.19-server.txt)

[crash-2020-10-04_22.25.16-client.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5325238/crash-2020-10-04_22.25.16-client.txt)

**Comment by MLMII** [comment]
Just a quick update; the crash also exists in 0.6.2

**Comment by Dunkmania101** [comment]
Well, I honestly have no idea what's happening! I've tested this a bit with X's Minimap with no issues, but I saw something about it in the crash report that I only really understood to be about a class called "xaero_chunkclass". I can only guess what that's for without looking at its code, since I'm not that mod's author. Anyway, this led me to notice another slight issue with the harvesters, so I'll fix that. I'll leave this open for now, since I probably haven't fixed whatever is going on, if it's even on my end. If X's mod is updated and it stops, please close this issue. Thanks!

**Comment by MLMII** [comment]
Kay, will do; thank you.

**Comment by Taccio33** [comment]
I checked without Xaero (mini and large map), with a fresh world both in forge 34.1.0 and 34.1.5
[crash-2020-10-05_08.59.53-client.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5325922/crash-2020-10-05_08.59.53-client.txt)
[crash-2020-10-05_08.54.31-server.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5325923/crash-2020-10-05_08.54.31-server.txt)
[crash-2020-10-05_09.08.38-client.txt](https://github.com/Dunkmania101/SpatialHarvesters/files/5325924/crash-2020-10-05_09.08.38-client.txt)

**Comment by Dunkmania101** [comment]
I may have found something! The crash reports all seemed to be complaining about a method called "setOutputs", which basically sets clears a list of items and adds a new set of items to it. I noticed, however, that when the variable that is the list is first created, it's only initialized, which basically means it isn't given a specific value and I think is just made null, or basically empty or nothing. I think that would mean that when the method would try to, say, add things to it, it would see a null variable and not know what to do but crash. Assuming that's the case, I have no idea how it didn't crash for me. I'll leave this open for now, since I never actually got those issues, so you guys should probably be the ones to test. Thanks!

**Comment by Taccio33** [comment]
Thanks for the time you're taking. As of 15 minuts of testing the world (old and new) work, and do not crash on opening or using the mod, and that's great! 
on the other hand... the mob harvester seems to not harvest, and that's strange. I even tried changing the configs to make one machine extremely fast and one slow (just to be sure) and they don't work. 
in the mean time real thanks for the mod and the work you're putting in. 
Edit: the other ones works but they where slow, I increased the tick speed and then reset the configs. The mob harvester still doesnt work.

**Comment by Dunkmania101** [comment]
Whoof, that's a relief! I thought, based on your original comment, that I'd have to figure out why none of the Harvesters were working! Anyway, I figured out why the Mob Harvester was broken and fixed it. I'll close this, thanks!
